### ISSUE TITLE
Any chances of getting this one in https://pypi.org/?

### ISSUE THREAD

**Issue by FrancescElies** [austinbhale/Clang-Visualizer#1]
I know this is a small script and just copying it is enough.

But I could envision the following workflow pretty comfortable.

```
pip install clang-visualizer
python -m clang_visualizer [newfile.log]
```

**Comment by austinbhale** [comment]
Great idea! I updated the script and added it to pypi @[clang-html](https://pypi.org/project/clang-html/1.3.0/)

The following should be working now:
```
pip install clang-visualizer
python -m clang_visualizer [newfile.log]
```
