### ISSUE TITLE
What is that button parameter for?

### ISSUE THREAD

**Issue by FrancescElies** [austinbhale/Clang-Visualizer#3]
Hi,

I read the readme but I don't really get what is that `button` thingy for. 
Could you explain me in a sentence what is that Doxygen button for?

Best & thanks

**Comment by austinbhale** [comment]
The original client wanted an option to link to their own documentation, which doesn't seem that helpful in a general case.

I just updated the script to point to the official clang docs for each check, like so in the new example: https://austinbhale.com/Clang-Visualizer/examples/clang.html

**Comment by FrancescElies** [comment]
Awesome, thanks! The button to clang docs makes sense 👌
