### ISSUE TITLE
Lack of support for clang-tidy --use-color

### ISSUE THREAD

**Issue by Abergard** [austinbhale/Clang-Visualizer#5]
run-clang-tidy for LLVM version 12.0.0 use colors by default and the generated html looks like below:

[0m[0;1;31merror: [0m[1mno matching function for call to 'IsValid' [clang-diagnostic-error][0m
                if (IsValid(InstigatorChar->InterruptOffense) == true) {
[0;1;32m  

Is it a way to display colors in the generated HTML page?

**Comment by austinbhale** [comment]
Thanks to @virtualthoughts for implementing this feature in #6.

Update to PyPI with a new release will be made shortly.
